server:
  port: 8102
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: usian-order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    cluster:
      nodes:
        - 192.168.2.130:7001
        - 192.168.2.130:7002
        - 192.168.2.130:7003
        - 192.168.2.130:7004
        - 192.168.2.130:7005
        - 192.168.2.130:7006
    jedis:
      pool:
        max-active: 20  #连接池最大连接数
        max-idle: 10  #连接池最大空闲数
        min-idle: 5  #连接池最小空闲数
  rabbitmq:
    host: 192.168.2.131
    username: admin
    password: 1111
    virtual-host: /
    publisher-confirms: true #开启消息确认机制
    publisher-returns: true #开启发送失败退回

#订单
ORDER_ID_KEY: ORDER_ID_KEY
ORDER_ID_BEGIN: 100544
ORDER_ITEM_ID_KEY: ORDER_ITEM_ID_KEY